name=input("Enter your name:")
clas=int(input("Enter your class:"))
section=input("Enter your section:")
USN=input("Enter your USN:")
print("Hello")
print("My name is",name)
print("I am from class",clas)
print("Section",section)
print("USN:",USN)